---
- name: Update apt
  apt: update_cache=yes

- name: Install Sys Packages
  apt: name={{ item }} state=latest
  with_items: sys_packages

- name: Make sure python-software-properties is installed
  apt: name=python-software-properties state=latest

- name: Add ppa Repository
  apt_repository: repo='ppa:ondrej/php'

- name: Update apt
  apt: update_cache=yes
